### ISSUE TITLE
Add Contrubuting.md file in order to not getting disqualified from hacktober fest

### ISSUE THREAD

**Issue by akanshbende** [navendu-pottekkat/navendu-pottekkat.github.io#105]

**Comment by pottekkat** [comment]
You don't need to add CONTRIBUTING.md. Also this is a personal project and its intended use is to be forked and used.

**Comment by akanshbende** [comment]
No I am talking about participating in hacktober fest,where you are maintainer of repo and has to follow this rules :

https://hacktoberfest.com/participation/#maintainers

**Comment by pottekkat** [comment]
Yes. Those are just best practices. I don't want to keep this project open to contribution in general because it is my personal site.

**Comment by akanshbende** [comment]
Okay No issues,Just saw hacktoberfest label on your repo thats why assumeg that its open source
