### ISSUE TITLE
#Feature-Request: Dark Light mode toggle

### ISSUE THREAD

**Issue by Mdfarhan9304** [navendu-pottekkat/navendu-pottekkat.github.io#106]
I would like to suggest adding a dark/light mode toggle to the website. This feature would provide users with the option to switch between dark and light themes, making the website more accessible and user-friendly in different lighting conditions.

**Comment by Mdfarhan9304** [comment]
Assign me this issue

**Comment by pottekkat** [comment]
It already has that feature. I have chosen to disable it because of personal preferences. Thank you for opening the issue.
