### ISSUE TITLE
Updating blogs according to 2022

### ISSUE THREAD

**Issue by mohammedyaqub** [navendu-pottekkat/navendu-pottekkat.github.io#14]
Could you please update your blogs contributing to open source as per 2022

**Comment by pottekkat** [comment]
The [open source internship programs](https://navendu.me/posts/open-source-internship-programs/) blog?

**Comment by mohammedyaqub** [comment]
Exactly:)

**Comment by pottekkat** [comment]
@mohammedyaqub Could you mention what changes need to be made?
