### ISSUE TITLE
Error on serve

### ISSUE THREAD

**Issue by Tytan-Codes** [navendu-pottekkat/navendu-pottekkat.github.io#140]
When i clone and then run ```hugo server```i get this:

```
Error: error building site: process: readAndProcessContent: "/Users/tytan/code/personal-website/content/daily/1-3-22-working-in-open-source.md:17:1": failed to extract shortcode: template for shortcode "collapse" not found
```

i am wondering how to fix this.

Sorry for the novice question.

-Tytan

**Comment by pottekkat** [comment]
Hmm, the collapse shortcode is available in the PaperMod theme at `/layouts/shortcodes/collapse.html`

```
{{ if .Get "summary" }}
{{ else }}
{{ warnf "missing value for param 'summary': %s" .Position }}
{{ end }}
<p><details {{ if (eq (.Get "openByDefault") true) }} open=true {{ end }}>
  <summary markdown="span">{{ .Get "summary" | markdownify }}</summary>
  {{ .Inner | markdownify }}
</details></p>
```

So this should not error out.

I would suggest using the PaperMod theme directly because this is heavily customized.

**Comment by Tytan-Codes** [comment]
well, i just downloaded and ran hugo serve so i don't know what could go wrong.

**Comment by Tytan-Codes** [comment]
![image](https://github.com/pottekkat/personal-website/assets/91703892/a213dfc2-b06c-482e-a9a9-00ee85be5989)
are you sure it's there? Also if it is, and i'm just not seeing it, im sorry, i am completely new to this stuff.

Also can you walk me through cloning the repo so getting it to localy serve please.

**Comment by pottekkat** [comment]
1. I suggest you try following the guide from PaperMod: https://adityatelange.github.io/hugo-PaperMod/
2. The shortcode is already included in the theme: https://github.com/adityatelange/hugo-PaperMod/blob/031e2ba57ea2b7b1de2e73c20bf2b5716f654fac/layouts/shortcodes/collapse.html

**Comment by Tytan-Codes** [comment]
could you please give me instructions on what to do after cloning your amazing repo. 
like how to serve properly and that kinda thing
Again, i'm really story for how noobie this is.

**Comment by pottekkat** [comment]
Again, this isn't meant to be used directly. Just running Hugo would work. Going through the Hugo docs would be the first step.

If you like to use this, then use the PaperMod theme and follow the instructions I shared in my previous comment.

**Comment by Tytan-Codes** [comment]
Ok thanks

**Comment by Tytan-Codes** [comment]
# SOVED

When you clone you need to clone with 

```git clone``` **```--recurse-submodules --no-single-branch```** ```what every you want to clone```
